language: python
# Run on Travis CI's docker infrastructure
sudo: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27 CC=gcc
    - python: 3.5
      env: TOXENV=py35 CC=gcc
    - python: 2.7
      env: TOXENV=py27 CC=clang
    - python: 3.5
      env: TOXENV=py35 CC=clang

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

addons:
    postgresql: "9.4"

services:
    - memcached
    - postgresql

before_install:
    - pip install -U pip setuptools pbr
    - pip --version
    - export VE=$VIRTUAL_ENV  # Use the virtual environment travis provides.
    - cp etc/pip.conf $VE

install:
    - createdb -E UTF8 -O travis weasyl_test
    - test "$TOXENV" ">" py3 || make -B ${VE}
    - make -C libweasyl .stamp-ve .stamp-egg-info

script:
    - test "$TOXENV" ">" py3 || make test
    - make -C libweasyl test
